plugins {
    id 'com.android.application'
}

android {
    namespace 'com.translator.ai'
    compileSdk 34

    defaultConfig {
        applicationId "com.translator.ai"
        minSdk 21
        targetSdk 34
        versionCode 3
        versionName "1.0.2"
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "AI_智能翻译_v${variant.versionName}.apk"
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // Pure lightweight, no heavy dependencies needed for WebView container
}
